GET http://localhost:3000/users/David

###
GET http://localhost:3000/users?userId=lorna

###
POST http://localhost:3000/getToken
Content-Type: application/json

{
    "firstName": "first-name",
    "password": "user-password"
}

###
GET http://localhost:3000/cards
Authorization: Bearer 
// Get cards by details. Can also be used to send single terms (such as rarrity=Rare or type=Fighter) 
// and two terms (like rarity=Common&type=Creature) to get more general lists of cards.
###
GET http://localhost:3000/cards/search?rarity=Common&type=Fighter&set=Time%20is%20Right%20Set
Authorization: Bearer 

// Get card amount
###
GET http://localhost:3000/cards/count
Authorization: Bearer 
// Get a random card
###
GET http://localhost:3000/cards/random
Authorization: Bearer 
// Update a card by ID
###
PUT http://localhost:3000/cards
Authorization: Bearer 

{
    "cardId": 1,
    "name": "Updated Card Name",
    "description": "Updated Card Description"
}

###
POST http://localhost:3000/cards/create
Authorization: Bearer 

{
    "name": "Name",
    "description": "New Card Description"
}

###
DELETE http://localhost:3000/cards
Authorization: Bearer 
Content-Type: application/json

{
    "cardId": 4
}
